[build]
  command = "hugo"
  publish = "public"
  functions = "netlify/functions"

[context.production.environment]
  HUGO_VERSION = "0.124.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.124.1"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.124.1"